detyreASPmvc/Controllers/ShitjetController.cs
using detyreASPmvc.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using detyreASPmvc.CustomModel;

namespace detyreASPmvc.Controllers
{
    public class ShitjetController : Controller
    {
        // GET: Shitjet
        db_TeDhenat db = new db_TeDhenat();
        
        public ActionResult Shitja()//shitjaKerko
        {
            var tedhenat = from r in db.ProductStock select r;
            
            return View("Shitja", tedhenat.ToList());
        }

        [HttpPost]
        public ActionResult KerkoProdDisponueshme(string Search, string searchBy)//shitjaKerko
        {
            var tedhenat = from r in db.ProductStock select r;
            if (!String.IsNullOrEmpty(Search) || !String.IsNullOrEmpty(searchBy))
            {
                Search = Search.Trim();
                searchBy = searchBy.Trim();
                switch (searchBy)
                {
                    case "0": tedhenat = tedhenat.Where(i => i.Barcode.ToString().StartsWith(Search)); break;
                    case "1": tedhenat = tedhenat.Where(i => i.ProductName.ToString().StartsWith(Search)); break;
                    case "2": tedhenat = tedhenat.Where(i => i.Description.ToString().StartsWith(Search)); break;
                }
            }
            return PartialView("_Shitja",  tedhenat.ToList());
        }

        [HttpPost]
        public ActionResult ShiteProduktin(string _Barcode)//Shite
        {
            if (_Barcode == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (String.IsNullOrEmpty(_Barcode))
            {
                return HttpNotFound();
            }
            int _iBarcode = Convert.ToInt32(_Barcode);
            int id = db.ProductStock.Where(c => c.Barcode == _iBarcode).Select(c => c.ProdID).FirstOrDefault();
            
            ProductStock _prStockDB = db.ProductStock.Find(id);

            if (_prStockDB ==null)
            {
                return HttpNotFound();
            }
            ProductStock_cust prCostum = new ProductStock_cust()
            {
                ProdID = _prStockDB.ProdID,
                Barcode = _prStockDB.Barcode,
                ProductName = _prStockDB.ProductName,
                Description = _prStockDB.Description,
                Quantity = _prStockDB.Quantity,
                UnitPrice = _prStockDB.UnitPrice,
                IsDeleted = _prStockDB.IsDeleted,
                DateRegister = _prStockDB.DateRegister,
                DateModified = _prStockDB.DateModified
            };
            return View(prCostum);
        }

        [HttpPost]
        public ActionResult KonfirmojShitjen([Bind(Include = "ProdID,Barcode,ProductName,Description,Quantity,UnitPrice,IsDeleted,DateRegister,DateModified,QuantitySold")]ProductStock_cust _pr)
        {
            //if (ModelState.IsValid)
            //{
            try
            {
                ProductStock _prDBStock = new ProductStock() 
                {
                    ProdID = _pr.ProdID,
                    Barcode = _pr.Barcode,
                    ProductName = _pr.ProductName,
                    Description = _pr.Description,
                    Quantity = (double)(_pr.Quantity - _pr.QuantitySold),
                    UnitPrice = _pr.UnitPrice,
                    IsDeleted = _pr.IsDeleted,
                    DateRegister = _pr.DateRegister,
                    DateModified = DateTime.Now
                };
                db.Entry(_prDBStock).State = EntityState.Modified;

                //ProductStock _prDB = db.ProductStock.Find(@ViewBag.ProdID);
                //_prDB.Quantity -= Convert.ToDouble(Quantity);

                ProductSold prSold = new ProductSold()
                {
                    ProdID = _pr.ProdID,
                    Quantity = (double)_pr.QuantitySold,
                    UnitPrice = _pr.UnitPrice,
                    TotalPrice = Convert.ToDecimal(_pr.QuantitySold) * _pr.UnitPrice,
                    DateSold = DateTime.Now
                };

                db.ProductSold.Add(prSold);
                db.SaveChanges();
            }
            catch (Exception ex /* dex */)
            {
                ModelState.AddModelError("", "E pamundur per t'u edituar. Provo me vone, nese ka probleme te reja kontakto me Adminin. Faleminderit!");
            }
            //}
            return RedirectToAction("TeShiturat");
        }

        public ActionResult TeShiturat()
        {
            var shitjet = from r in db.ProductSold select r;
            return View(shitjet.ToList());
        }
        [HttpPost]
        public async Task<ActionResult> KerkoTeShiturat(string Search, string searchBy)
       
        {
            var shitjet = from r in db.ProductSold select r;
            if (!String.IsNullOrEmpty(Search) || !String.IsNullOrEmpty(searchBy))
            {
                Search = Search.Trim();
                searchBy = searchBy.Trim();
                switch (searchBy)
                {
                    case "0": shitjet = shitjet.Where(i => i.ProductStock.Barcode.ToString().StartsWith(Search)); break;
                    case "1": shitjet = shitjet.Where(i => i.ProductStock.ProductName.ToString().StartsWith(Search)); break;
                    case "2": shitjet = shitjet.Where(i => i.ProductStock.Description.ToString().StartsWith(Search)); break;
                }
            }
            return View("_TeShitura",await shitjet.ToListAsync());
        }

        public ActionResult Edito(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductSold _prDB = db.ProductSold.Find(id);
            if (String.IsNullOrEmpty(id.ToString()))
            {
                return HttpNotFound();
            }

            return View(_prDB);
        }

        [HttpPost, ActionName("Edito")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirmed([Bind(Include = "SoldID,ProdID, Barcode,Quantity,UnitPrice,TotalPrice,DateSold")]ProductSold _pr)
        {
            try
            {
                db.Entry(_pr).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("TeShiturat");
            }
            catch (Exception ex /* dex */)
            {
                ModelState.AddModelError("", "E pamundur per t'u edituar. Provo me vone, nese ka probleme te reja kontakto me Adminin. Faleminderit!");
            }

            return View(_pr);
        }
        public ActionResult Detale(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductSold _pr = db.ProductSold.Find(id);
            if (_pr == null)
            {
                return HttpNotFound();
            }
            return View(_pr);
        }

        public ActionResult Fshije(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductSold _pr = db.ProductSold.Find(id);
            if (_pr == null)
            {
                return HttpNotFound();
            }
            return View(_pr);
        }

        // POST: 
        [HttpPost, ActionName("Fshije")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductSold _pr = db.ProductSold.Find(id);
            try
            {
                db.Entry(_pr).State = EntityState.Deleted;
                db.SaveChanges();
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "E pamundur per t'u fshire. Provo me vone,nese ka probleme te reja kontakto me Adminin. Faleminderit!");
            }
            return RedirectToAction("TeShiturat");
        }

    }
}

detyreASPmvc/Views/Shitjet/Detale.cshtml
@model detyreASPmvc.Models.ProductSold

@{
    ViewBag.Title = "Detale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detale</h2>

<div>
    <h4>ProductSold</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductStock.Barcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductStock.Barcode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductStock.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductStock.ProductName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductStock.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductStock.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateSold)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateSold)
        </dd>

        

    </dl>
</div>
<p>
    @Html.ActionLink("Edito", "Edito", new { id = Model.SoldID }) |
    @Html.ActionLink("Kthehu prapa", "TeShiturat")
</p>

detyreASPmvc/Views/Shitjet/Edito.cshtml
@model detyreASPmvc.Models.ProductSold

@{
    ViewBag.Title = "Edito te shiturat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edito tabelen e te shiturave</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SoldID)        
        @Html.HiddenFor(model => model.ProdID)
        @Html.HiddenFor(model => model.ProductStock.Barcode)        
        @Html.HiddenFor(model => model.DateSold)

        

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>
        @* cmimi tot behet me jquery ose js *@
        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ruaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Kthehu prapa", "TeShiturat")
</div>

detyreASPmvc/Views/Shitjet/Fshije.cshtml
@model detyreASPmvc.Models.ProductSold

@{
    ViewBag.Title = "Fshije";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Fshije produktin e shitur</h2>

<h3>A jeni te sigurte per t'a fshire kete shitje?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductStock.Barcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductStock.Barcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateSold)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateSold)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductStock.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductStock.ProductName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Fshije" class="btn btn-default" /> |
            @Html.ActionLink("Kthehu prapa", "TeShiturat")
        </div>
    }
</div>

detyreASPmvc/Views/Shitjet/ShiteProduktin.cshtml
@model detyreASPmvc.CustomModel.ProductStock_cust

@{
    ViewBag.Title = "ShiteProduktin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<h2>Shite</h2>
<script>
    $(document).ready(function () {
    });

    function CalcPrice() {
        var unitPrice = $("#UnitPrice").val();  @*unitPrice = @Model.UnitPrice;*@
        var editQuantity = $("#editQuantity").val();//editQuantity = document.getElementById("editQuantity").value; @*// NUK BENE @ViewBag.sellQuantity = editQuantity;*@
        $("#TotPrice").val(unitPrice * editQuantity);  //document.getElementById("TotPrice").value = unitPrice * editQuantity;
     }
</script>
<hr />
@using (Html.BeginForm("KonfirmojShitjen", "Shitjet", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true) @*, "", new { @class = "text-danger" })labelat me i ba disabled textboxa*@
        @Html.HiddenFor(model => model.ProdID)
        @Html.HiddenFor(model => model.Barcode)
        @Html.HiddenFor(model => model.ProductName)
        @Html.HiddenFor(model => model.Description)
        @Html.HiddenFor(model => model.UnitPrice)
        @Html.HiddenFor(model => model.Quantity)
        @Html.HiddenFor(model => model.IsDeleted)
        @Html.HiddenFor(model => model.DateRegister)
        @Html.HiddenFor(model => model.DateModified)
        @{ViewBag.ProdID = Model.ProdID;}@*new { htmlAttributes =  new{ @class = "control-label col-md-2" })*@
        <div class="form-group">
            @Html.LabelFor(model => model.Barcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Barcode, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.QuantitySold, htmlAttributes: new { @class = "control-label col-md-2" }) @*ose editor "*@
            <div class="col-md-10">
                @*@Html.TextBox("QuantitySold", null, new {@class = "form-control", @id = "editQuantity", @onchange = "CalcPrice();", @type = "number" })*@
                @Html.EditorFor(model => model.QuantitySold,new { htmlAttributes =new { @class = "form-control", @id = "editQuantity", @onchange = "CalcPrice();", @type = "number" }})
                @Html.ValidationMessageFor(model => model.QuantitySold, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control", @id = "UnitPrice" } })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Price", htmlAttributes: new { @class = "control-label col-md-2", @id = "shemb" })
            <div class="col-md-10">
                @Html.TextBox("TotalPrice", null, new { @readonly = true, @id = "TotPrice", @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="OK shite" class="btn btn-primary btn-xs" />
                @Html.ActionLink("Kthehu prapa", "Shitja", null, new { @class = "btn btn-info btn-xs" })
            </div>


        </div>

    </div>
            }

<p style="margin-left:197px">
    @*@("OK shite", "KonfirmojShitjen", "Home", new { Quantity=Model.Quantity @*id = Model.ProdID*@

</p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

detyreASPmvc/Views/Shitjet/Shitja.cshtml
@model IEnumerable<detyreASPmvc.Models.ProductStock>
@{
    ViewBag.Title = "Shitja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>

    function KontrolloPerValidim() {
        var barcode = document.getElementById("txtShitBarcode").value;
        var re = new RegExp("^[0-9]{6,6}$"); //{5,5} per eventin onkeypress
        //$("#btnSHITE").attr.disabled=false;
        if (re.test(barcode)) {
            document.getElementById("btnSHITE").disabled = false;
        } else {
            document.getElementById("btnSHITE").disabled = true;
        }
        document.getElementById("btnSHITE").disabled = !re.test(barcode);
    }

    $(document).ready(function () {
        $("#searchBy").change(function () {
            var val = $(this).val();
            if (val == "0") {
                $("#txtKerko").attr("placeholder", "Shtyp Barcode").val("").focus().blur();
                $("#txtKerko").attr('type', 'number');
            } else if (val == "1") {
                $("#txtKerko").attr("placeholder", "Shtyp emrin e produktit").val("").focus().blur();
                $("#txtKerko").attr('type', 'text');
            } else if (val == "2") {
                $("#txtKerko").attr("placeholder", "Shtyp pershkrimin").val("").focus().blur();
                $("#txtKerko").attr('type', 'text');
            }
        });
    });

    $(document).ready(function () {
        $("#prodDisponueshme").click(function () { //prodDisponueshme
            $("#pnlproduktet").fadeToggle("slow");  // $("#div1").fadeToggle(); ose 3000 per 3sec
        });
    });
</script>
<style>
    #prodDisponueshme:hover {
        cursor: pointer;
    }
</style>
<br/>
<div class="panel panel-default">
    <div class="panel-body">
        <div>
            @using (Html.BeginForm("ShiteProduktin", "Shitjet", FormMethod.Post))
            {
            <div class="form-group">
                <label class="control-label">Improvizimi i marketit</label>
                <div class="input-group">
                    <span class="input-group-addon" style="background-color: #7EBCA9; color:white">Barcode:</span>
                    @Html.TextBox("_Barcode", null, new { @class = "form-control", @id = "txtShitBarcode", @type = "number", @onchange = "KontrolloPerValidim();" })

                    <span class="input-group-btn">
                        <button type="submit" disabled="true" id="btnSHITE" class="btn" style="margin-right: 724px; background-color: #7EBCA9; color:white"> Shite</button>
                    </span>
                </div>
            </div>
            }
        </div>

    </div>
</div>
<br />
<div class="panel panel-info">
    <div class="panel-heading" style="background-color: #A3DBF1;">
        <h3 class="panel-title" id="prodDisponueshme">Produktet e disponueshme</h3>
    </div>
    <div class="panel-body" id="pnlproduktet" style="display:none">
        <div class="panel panel-default">
            <div class="panel-body">
                
                @using (Ajax.BeginForm("KerkoProdDisponueshme", "Shitjet", new AjaxOptions{ InsertionMode = InsertionMode.Replace, UpdateTargetId = "tblRezulatet"}))
                {
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" style="background-color:#A3DBF1; color:white">Kerko sipas: </span>
                            <select class="form-control" name="searchBy" id='searchBy' style="width: 150px">
                                <option value="0">Barcode</option>
                                <option value="1">Emri produktit</option>
                                <option value="2">Pershkrimit</option>
                            </select>
                            @Html.TextBox("Search", null, new { @id="txtKerko", @type = "number", placeholder = "Shtyp Barcode", @class = "form-control" })
                            <span class="input-group-btn">
                                <button type="submit" class="btn" id="btnKerko" style="margin-right: 486px; background-color: #A3DBF1; color:white">Kerko</button>
                            </span>
                        </div>
                    </div>
                }
            </div>
        </div>

        <section id="tblRezulatet">
            @Html.Partial("_Shitja", Model)
        </section>


    </div>
</div>

detyreASPmvc/Views/Shitjet/TeShiturat.cshtml
@model IEnumerable<detyreASPmvc.Models.ProductSold>

@{
    ViewBag.Title = "Te shiturat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Te shiturat</h2>
<link href="~/Content/Site.css" rel="stylesheet"/>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>
    $(document).ready(function() {
        $("#searchBy").change(function() {
            var val = $(this).val();
            if (val == "0") {
                $("#txtKerko").attr("placeholder", "Shtyp Barcode").val("").focus().blur();
                $("#txtKerko").attr('type', 'number');
            } else if (val == "1") {
                $("#txtKerko").attr("placeholder", "Shtyp emrin e produktit").val("").focus().blur();
                $("#txtKerko").attr('type', 'text');
            } else if (val == "2") {
                $("#txtKerko").attr("placeholder", "Shtyp pershkrimin").val("").focus().blur();
                $("#txtKerko").attr('type', 'text');
            }
        });
    });
</script>

<br />
<div class="panel panel-default">
    <div class="panel-body">
        @using (Ajax.BeginForm("KerkoTeShiturat", "Shitjet", new AjaxOptions
        { InsertionMode = InsertionMode.Replace, UpdateTargetId = "tblRezulatet" }))
        {
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon" style="background-color: #7EBCA9; color: white">Kerko sipas: </span>
                    <select class="form-control" name="searchBy" id='searchBy' style="width: 150px">
                        <option value="0">Barcode</option>
                        <option value="1">Emri produktit</option>
                        <option value="2">Pershkrimit</option>
                    </select>
                    @Html.TextBox("Search", null, new {@id = "txtKerko", @type = "number", placeholder = "Shtyp Barcode", @class = "form-control"})
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn" style="margin-right: 518px; background-color: #7EBCA9; color: white">Kerko</button>
                    </span>
                </div>
            </div>
        }
    </div>
</div>
<div class="panel panel-success" >
    <div class="panel-heading"  style="background-color: #7EBCA9">
        <h3 class="panel-title">Produktet e shitura</h3>
    </div>
    <div class="panel-body">
        <section id="tblRezulatet">
            @Html.Partial("_TeShitura", Model)
        </section>

      
    </div>
</div>

detyreASPmvc/Views/Shitjet/_Shitja.cshtml
@model IEnumerable<detyreASPmvc.Models.ProductStock>


<table class="table table-striped table-hover">
    @{
        if (Model.Count() == 0)
        {
            <tr>
                <b>
                    <p style="color: Red">Nuk ka produkte</p>
                </b>
            </tr>
        }
        else
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Barcode)
                </th>
                <th>
                    Emri produktit
                </th>
                <th>
                    Pershkrimi
                </th>
                <th>
                    Sasia
                </th>
                <th>
                    Cmimi njesi
                </th>
                <th>

                </th>
            </tr>
            foreach (var item in Model)
            {
                if (item.IsDeleted != true)
                {
                    if (item.Quantity != 0) //nuk ka negative => vetem ato > 0
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Barcode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitPrice)
                            </td>
                            <td></td>
                        </tr>

                    }
                }
            }
        }
    }
</table>

detyreASPmvc/Views/Shitjet/_TeShitura.cshtml
@model IEnumerable<detyreASPmvc.Models.ProductSold>

<table class="table table-striped table-hover">
    @if (Model.Count() == 0)
            {
        <tr>
            <b>
                <p style="color: Red">Nuk ka produkte te shitura</p>
            </b>
        </tr>
    }

    else
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductStock.Barcode)
            </th>
            <th>
                Emri i produktit
            </th>
            <th>
                Pershkrimi
            </th>
            <th>
                Sasia
            </th>
            <th>
                Cmimi Njesi
            </th>
            <th>
                Cmimi total
            </th>
            <th>
                Data e shitjes
            </th>

            <th>Mundesi</th>
        </tr>


        decimal PriceTotal = 0, UnitPriceTotal = 0;
        double QuantityTotal = 0;

        foreach (var item in Model)
        {
            UnitPriceTotal += item.UnitPrice;
            QuantityTotal += item.Quantity;
            PriceTotal += item.TotalPrice;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductStock.Barcode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductStock.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductStock.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateSold)
                </td>

                <td>
                    @Html.ActionLink("Edito", "Edito", new { id = item.SoldID }, new { @class = "btn btn-warning btn-xs" })
                    @Html.ActionLink("Detale", "Detale", new { id = item.SoldID }, new { @class = "btn btn-info btn-xs" })
                    @Html.ActionLink("Fshije", "Fshije", new { id = item.SoldID }, new { @class = "btn btn-danger btn-xs" })
                </td>
            </tr>
        }
        <tr style="background-color: powderblue; color: black">
            <td colspan="3"><b>Total:</b></td>
            <td><b>@QuantityTotal</b></td>
            <td><b>@UnitPriceTotal</b></td>
            <td><b>@PriceTotal</b></td>
            <td></td>
            <td></td>
        </tr>
    }
</table>